# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superrod_new.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtOpenGL import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #context = QGLContext(QGLFormat())
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget_data = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_data.setStyleSheet("")
        self.tabWidget_data.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_data.setObjectName("tabWidget_data")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_load_data = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_load_data.setObjectName("pushButton_load_data")
        self.horizontalLayout_2.addWidget(self.pushButton_load_data)
        self.pushButton_append_data = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_append_data.setObjectName("pushButton_append_data")
        self.horizontalLayout_2.addWidget(self.pushButton_append_data)
        self.pushButton_delete_data = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_delete_data.setObjectName("pushButton_delete_data")
        self.horizontalLayout_2.addWidget(self.pushButton_delete_data)
        self.pushButton_save_data = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.horizontalLayout_2.addWidget(self.pushButton_save_data)
        self.pushButton_calculate = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.horizontalLayout_2.addWidget(self.pushButton_calculate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget_data = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_data.setObjectName("tableWidget_data")
        self.tableWidget_data.setColumnCount(0)
        self.tableWidget_data.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_data)
        self.tabWidget_data.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.comboBox_dataset = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_dataset.setObjectName("comboBox_dataset")
        self.horizontalLayout_10.addWidget(self.comboBox_dataset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.tableWidget_data_view = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_data_view.setObjectName("tableWidget_data_view")
        self.tableWidget_data_view.setColumnCount(0)
        self.tableWidget_data_view.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_data_view)
        self.tabWidget_data.addTab(self.tab_6, "")
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_plot_style = QtWidgets.QPushButton(self.frame)
        self.pushButton_plot_style.setObjectName("pushButton_plot_style")
        self.horizontalLayout_3.addWidget(self.pushButton_plot_style)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMaximumSize(QtCore.QSize(16666666, 16777215))
        self.tabWidget.setStyleSheet("color: rgb(85, 85, 0);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_data = GraphicsLayoutWidget(self.tab)
        self.widget_data.setObjectName("widget_data")
        self.horizontalLayout_5.addWidget(self.widget_data)
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_fom = GraphicsLayoutWidget(self.tab_7)
        self.widget_fom.setObjectName("widget_fom")
        self.horizontalLayout_6.addWidget(self.widget_fom)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_pars = GraphicsLayoutWidget(self.tab_8)
        self.widget_pars.setObjectName("widget_pars")
        self.horizontalLayout_7.addWidget(self.widget_pars)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_fom_scan = GraphicsLayoutWidget(self.tab_2)
        self.widget_fom_scan.setObjectName("widget_fom_scan")
        self.horizontalLayout_8.addWidget(self.widget_fom_scan)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        #self.widget_edp = MSViewer(context,self.tab_4)
        #context.makeCurrent()
        #self.widget_edp.setObjectName("widget_edp")
        #self.horizontalLayout_9.addWidget(self.widget_edp)
        self.tabWidget.addTab(self.tab_4, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(200, 400))
        self.tabWidget_2.setStyleSheet("color: rgb(85, 79, 255);")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_pars = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_pars.setObjectName("tableWidget_pars")
        self.tableWidget_pars.setColumnCount(0)
        self.tableWidget_pars.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_pars)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_load_table = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_load_table.setObjectName("pushButton_load_table")
        self.horizontalLayout_11.addWidget(self.pushButton_load_table)
        self.pushButton_save_table = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_save_table.setObjectName("pushButton_save_table")
        self.horizontalLayout_11.addWidget(self.pushButton_save_table)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit_script = QCodeEditor(self.tab_9)
        self.plainTextEdit_script.setObjectName("plainTextEdit_script")
        self.verticalLayout_5.addWidget(self.plainTextEdit_script)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_load_script = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_load_script.setObjectName("pushButton_load_script")
        self.horizontalLayout_4.addWidget(self.pushButton_load_script)
        self.pushButton_save_script = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_save_script.setObjectName("pushButton_save_script")
        self.horizontalLayout_4.addWidget(self.pushButton_save_script)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFit = QtWidgets.QMenu(self.menubar)
        self.menuFit.setObjectName("menuFit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSimulate = QtWidgets.QAction(MainWindow)
        self.actionSimulate.setObjectName("actionSimulate")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSimulate)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(MainWindow)
        self.tabWidget_data.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load_data.setText(_translate("MainWindow", "LoadData"))
        self.pushButton_append_data.setText(_translate("MainWindow", "AppendData"))
        self.pushButton_delete_data.setText(_translate("MainWindow", "DeleteData"))
        self.pushButton_save_data.setText(_translate("MainWindow", "SaveData"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget_data.setTabText(self.tabWidget_data.indexOf(self.tab_5), _translate("MainWindow", "Data"))
        self.label.setText(_translate("MainWindow", "Data set:"))
        self.tabWidget_data.setTabText(self.tabWidget_data.indexOf(self.tab_6), _translate("MainWindow", "View"))
        self.label_2.setText(_translate("MainWindow", "FOM log: None"))
        self.pushButton_plot_style.setText(_translate("MainWindow", "PlotStyle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "FOM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Pars"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "FOM scans"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "EDP"))
        self.pushButton_load_table.setText(_translate("MainWindow", "LoadTable"))
        self.pushButton_save_table.setText(_translate("MainWindow", "SaveTable"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Grid"))
        self.pushButton_load_script.setText(_translate("MainWindow", "LoadScript"))
        self.pushButton_save_script.setText(_translate("MainWindow", "SaveScript"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Script"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuFit.setTitle(_translate("MainWindow", "Fit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSimulate.setText(_translate("MainWindow", "Simulate"))
        self.actionSimulate.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; text-decoration: underline;\">Simulate</span></p></body></html>"))
        self.actionSimulate.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Run</span></p></body></html>"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
from code_editor import QCodeEditor
from pyqtgraph import GraphicsLayoutWidget
from superrod_viewer import MSViewer
